// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJj4cLhsghhV-_U7YQhYkjZAO5PVEvCuw',
    appId: '1:890536806900:web:00d7d09620f58ba81451a1',
    messagingSenderId: '890536806900',
    projectId: 'belajar-clean',
    authDomain: 'belajar-clean.firebaseapp.com',
    storageBucket: 'belajar-clean.firebasestorage.app',
    measurementId: 'G-MWN1GN9ZCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDASbzruDXKCDWmKtDtRI5qpEXu3o5eg0',
    appId: '1:890536806900:android:d6321e90c89491071451a1',
    messagingSenderId: '890536806900',
    projectId: 'belajar-clean',
    storageBucket: 'belajar-clean.firebasestorage.app',
  );
}
